name: Awesome Selfhosted Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Run at 1 am every day

env:
  MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
  TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
  TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
  PAT: ${{ secrets.PAT }}

jobs:
  run-python-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Poetry Version
        run: poetry --version

      - name: Install Project
        run: poetry install --no-interaction

      - name: Run Python function
        run: poetry run python ./src/scrapers/github_awesome_self_hosted_scraper.py
