name: Awesome Selfhosted Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Run at 1 am every day

jobs:
  run-python-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Run Python function
        run: python ./src/scrapers/github_awesome_self_hosted_scraper.py
