name: Awesome Selfhosted Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Run at 1 am every day

jobs:
  run-python-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Poetry Version
        run: poetry --version

      - name: Run Python function
        run: poetry run python ./src/scrapers/github_awesome_self_hosted_scraper.py
