name: Build and Push Postgres to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy Postgres ${{ matrix.postgres_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: ["15", "16", "17"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/Dockerfile.postgres
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/custom-postgres:${{ matrix.postgres_version }}
          platforms: linux/amd64, linux/arm64
          build-args: |
              POSTGRES_VERSION: ${{ matrix.postgres_version }}
